name: Testing and Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Cache tox environments
      uses: actions/cache@v4
      with:
        path: .tox
        key: ${{ matrix.python-version }}-tox-${{ hashFiles('pyproject.toml', 'requirements-dev.txt') }}
    - name: Run Linter
      run: tox -e lint
    - name: Run Tests
      run: tox -e tests
